### ISSUE TITLE
Issue with path to preprocessor when the default shell is cmd.exe

### ISSUE THREAD

**Issue by Temetra** [mihar-22/svelte-jester#18]
Is it possible to change the single quotes around `${preprocessor}` in `transformer.js` to double quotes? I'm getting an error on my Windows machine when the project dir has a space.

```
Uncaught Error: Cannot find module 'M:\Projects\Svelte Projects\svelte-card-game\'M:\Projects\Svelte'

FROM

at Object.process (node_modules/svelte-jester/src/transformer.js:15:17)
at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:463:35)
at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:568:40)
at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:606:25)
```

I'm unable to test on other shells at the moment, but [Node documentation](https://nodejs.org/api/cli.html#cli_e_eval_script) suggests it should be fine. Can anyone confirm this issue?

**Comment by mihar-22** [comment]
Sorry about that fixed in `1.1.4` :)
